### ISSUE TITLE
Application Layout/Application Links Selected Issue

### ISSUE THREAD

**Issue by cavalka** [OpenNTF/XPagesExtensionLibrary#81] opened 2016-10-31 20:14 UTC
When using the Application Layout Control with Bootstrap theme the application links do not get an "active" class assigned if property of 'selected' or 'selection' have value of true.  Either issue in Bootstrap theme or in Application Layout control.

**Comment by briangleeson** [comment] 2017-05-16 11:51
Found the source of this issue. It is due to the method `makeSelectedActive` in [ApplicationLinksRenderer](https://github.com/OpenNTF/XPagesExtensionLibrary/blob/master/extlib/lwp/product/runtime/eclipse/plugins/com.ibm.xsp.theme.bootstrap/src/com/ibm/xsp/theme/bootstrap/renderkit/html/extlib/layout/tree/ApplicationLinksRenderer.java#L35) returning false. 

This appears to be a remnant of the original Bootstrap4XPages project, as you can see the same method returns false here: https://github.com/OpenNTF/Bootstrap4XPages/blob/master/eclipse/plugins/org.openntf.xsp.bootstrap/src/org/openntf/xsp/bootstrap/renderkit/html_extended/extlib/layout/tree/BootstrapApplicationLinksRenderer.java

Simple fix is to remove the method in ApplicationLinksRenderer and revert to the handling in the superclass. Only concern is any unexpected side effects, but it seems like it should be pretty clean.

**Comment by briangleeson** [comment] 2017-05-16 14:38
Closing as a duplicate of #79

**Closed by briangleeson** 2017-05-16 14:38 UTC
