### ISSUE TITLE
DDS interpretation of date values

### ISSUE THREAD

**Issue by almgun** [OpenNTF/XPagesExtensionLibrary#7] opened 2014-12-22 10:22 UTC
I’m using DDS to update Domino Documents via Http PATCH method
Sample-url: /pp.nsf/api/data/documents/unid/664D834FEF372CBCC1257D79005109EC
I use Chrome and the POSTMAN rest client plugin in this test
The data sent is on this format {"releasedEngMechanical1":"2013-02-20T12:18:18Z"}
releasedEngMechanical1 is defined as a field on the form specified by the form-field in the document

The date value is not interpreted correctly
1)	if I send 2014-02-20  , the date stored is 20’th of February as expected
2)	If I send 2014-02-03 , the date stored will be 2’nd of Mars !
It seems to me that the server side wants to use the last value in the string as the month part. When that is not possible (as in example 1) it tries to create a date “one way or the other” and therefore selects 20 as the date and 02 as month. 
It does not matter whether I provide a full date time string or not, the result is the same
It might be that setting other date definition setting on the server’s environment makes a difference; however that should not affect how this API is working

As a result, in my environment, any dates in the range 01-12 is interpreted incorrectly according to ISO 8601 Extended

**Comment by ddelay** [comment] 2015-01-05 17:58
JSON doesn't include a built-in datetime property type, so I think the data service is writing the data as text.  Instead of sending this:

    {"releasedEngMechanical1":"2013-02-20T12:18:18Z"}

Try sending this:

    {"releasedEngMechanical1":{"data":"2013-02-20T12:18:18Z", "type":"datetime"}}

Then the data service will write releasedEngMechanical1 as a datetime field.  

Also, when reading a document, you might want to specify this URL parameter:  strongtype=true.  That causes the data service to format datetime fields as shown in the second sample above.

**Comment by almgun** [comment] 2015-01-14 07:35
The **"type"="datetime"** does not change anything in my test environment
2013-02-20 will become 20th of February 2013 (good)
2014-02-10 will become 2'nd of October 2013 (bad) 
A field is interpreted as a date when there is a date-field on the form that matches the fieldname in JSON
The field match is case sensitive

**Comment by ddelay** [comment] 2015-01-14 15:10
OK.  I was able to reproduce the problem.  It happens for certain regional settings on the server OS.  For example, my Domino server is running on Windows.  I can reproduce the problem if my regional settings are French (France).  I cannot reproduce the problem if my regional settings are English (US).

The bottom line is __this looks like a defect__.  I will create a problem report and see if I can get it fixed in a future version of the extension library.  Meanwhile, the only work-around is to switch the regional settings on the server OS.  Sorry!

By the way, you may be correct about this:  "A field is interpreted as a date when there is a date-field on the form that matches the fieldname in JSON."  However, I still recommend explicitly declaring __"type": "datetime"__ when sending dates to the data service.  I think this is required when creating a new document.  It makes sense to use the same format for POST and PUT.

**Comment by padraic-edwards** [comment] 2016-01-04 21:19
Fixed by SPR DDEY9SRL6C. Closing this defect.

**Closed by padraic-edwards** 2016-01-04 21:19 UTC
